import "server-only";
import Database from "better-sqlite3";
import fs from "node:fs";
import path from "node:path";
import {products as seedProducts} from "@/lib/products";

const dbPath=process.env.DATABASE_PATH||path.join(process.cwd(),"data","guia-do-fone.sqlite");let connection:Database.Database|undefined;
type Migration={id:string;sql:string};
const migrations:Migration[]=[{id:"001_products",sql:`CREATE TABLE products (id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,brand TEXT NOT NULL,position INTEGER NOT NULL CHECK(position>0),category TEXT NOT NULL,badge TEXT NOT NULL,short_description TEXT NOT NULL,full_description TEXT NOT NULL,benefits TEXT NOT NULL,attention_points TEXT NOT NULL,specifications TEXT NOT NULL,recommended_for TEXT NOT NULL,not_recommended_for TEXT NOT NULL,affiliate_url TEXT NOT NULL,search_url TEXT NOT NULL,image_id TEXT,image_alt TEXT NOT NULL,is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0,1)),is_featured INTEGER NOT NULL DEFAULT 0 CHECK(is_featured IN (0,1)),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT); CREATE INDEX products_active_position ON products(is_active,position); CREATE INDEX products_featured ON products(is_featured);`},{id:"002_product_images",sql:`CREATE TABLE product_images (id TEXT PRIMARY KEY,original_name TEXT NOT NULL,mime_type TEXT NOT NULL CHECK(mime_type='image/webp'),width INTEGER NOT NULL,height INTEGER NOT NULL,size INTEGER NOT NULL,hash TEXT NOT NULL UNIQUE,data BLOB NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE INDEX product_images_hash ON product_images(hash);`}];
const affiliateMigration=[['soundcore-p30i','https://meli.la/31hbsds'],['jbl-wave-buds-2','https://meli.la/2EyM8zS'],['qcy-melobuds-pro','https://meli.la/246f3uU'],['soundcore-p20i','https://meli.la/3371j1i'],['redmi-buds-6-pro','https://meli.la/1Rscu23'],['jbl-tune-beam-2','https://meli.la/1oWBtxH'],['galaxy-buds3-pro','https://meli.la/2ugniMf'],['edifier-w820nb-plus','https://meli.la/2umHWe5'],['jbl-tune-770nc','https://meli.la/2Ekc4QE'],['sony-wh-1000xm5','https://meli.la/1LVvZz4']] as const;
function applyMigrations(conn:Database.Database){conn.exec("CREATE TABLE IF NOT EXISTS schema_migrations (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL)");const applied=new Set((conn.prepare("SELECT id FROM schema_migrations").all() as {id:string}[]).map(x=>x.id));const run=conn.transaction(()=>{for(const m of migrations)if(!applied.has(m.id)){conn.exec(m.sql);conn.prepare("INSERT INTO schema_migrations VALUES (?,?)").run(m.id,new Date().toISOString())}if(!applied.has("003_official_affiliate_links")){const found=conn.prepare(`SELECT slug FROM products WHERE slug IN (${affiliateMigration.map(()=>'?').join(',')})`).all(...affiliateMigration.map(x=>x[0])) as {slug:string}[];if(found.length!==affiliateMigration.length)throw new Error("Produtos do mapeamento de afiliados ausentes.");const update=conn.prepare("UPDATE products SET affiliate_url=?,updated_at=? WHERE slug=?");for(const [slug,url] of affiliateMigration)update.run(url,new Date().toISOString(),slug);conn.prepare("INSERT INTO schema_migrations VALUES (?,?)").run("003_official_affiliate_links",new Date().toISOString())}});run()}
function seed(conn:Database.Database){const count=(conn.prepare("SELECT count(*) count FROM products").get() as {count:number}).count;if(count)return;const insert=conn.prepare(`INSERT INTO products (id,name,slug,brand,position,category,badge,short_description,full_description,benefits,attention_points,specifications,recommended_for,not_recommended_for,affiliate_url,search_url,image_alt,is_active,is_featured,created_at,updated_at) VALUES (@id,@name,@slug,@brand,@position,@category,@badge,@description,@description,@benefits,@attention,@spec,@recommended,@notRecommended,@affiliate,@search,@alt,1,@featured,@updated,@updated)`);conn.transaction(()=>seedProducts.forEach(p=>insert.run({id:p.id,name:p.name,slug:p.slug,brand:p.brand,position:p.position,category:p.category,badge:p.badge,description:p.description,benefits:JSON.stringify(p.benefits),attention:JSON.stringify(p.limitations),spec:JSON.stringify({Tipo:p.type,Bateria:p.battery,ANC:p.anc,Codec:p.codec,Resistência:p.resistance,Multiponto:p.multipoint}),recommended:JSON.stringify(p.use),notRecommended:JSON.stringify(["Confirme especificações oficiais" ]),affiliate:p.affiliateUrl,search:p.searchUrl,alt:p.alt,featured:p.featured?1:0,updated:p.updatedAt})))()}
export function db(){if(connection)return connection;fs.mkdirSync(path.dirname(dbPath),{recursive:true});connection=new Database(dbPath,{timeout:5000});connection.pragma("journal_mode = WAL");connection.pragma("foreign_keys = ON");applyMigrations(connection);seed(connection);return connection}
export type DbProduct={id:string;name:string;slug:string;brand:string;position:number;category:string;badge:string;short_description:string;full_description:string;benefits:string;attention_points:string;specifications:string;recommended_for:string;not_recommended_for:string;affiliate_url:string;search_url:string;image_id:string|null;image_alt:string;is_active:number;is_featured:number;created_at:string;updated_at:string};
export const listProducts=(activeOnly=false)=>db().prepare(`SELECT * FROM products WHERE deleted_at IS NULL ${activeOnly?"AND is_active=1":""} ORDER BY position,name`).all() as DbProduct[];
export const productById=(id:string)=>db().prepare("SELECT * FROM products WHERE id=? AND deleted_at IS NULL").get(id) as DbProduct|undefined;
export const productBySlug=(slug:string)=>db().prepare("SELECT * FROM products WHERE slug=? AND deleted_at IS NULL AND is_active=1").get(slug) as DbProduct|undefined;
export const productStats=()=>db().prepare("SELECT sum(is_active=1) active,sum(is_active=0) inactive FROM products WHERE deleted_at IS NULL").get() as {active:number;inactive:number};
export const databasePath=dbPath;
export function closeDatabase(){if(connection){connection.close();connection=undefined}}
