export type Product={id:string;slug:string;position:number;name:string;brand:string;category:string;badge:string;description:string;benefits:string[];limitations:string[];type:"TWS"|"Headphone";battery:string;anc:string;codec:string;resistance:string;multipoint:string;use:string[];priceBand:string;image:string;alt:string;affiliateUrl:string;searchUrl:string;featured:boolean;updatedAt:string};
const search=(q:string)=>`https://lista.mercadolivre.com.br/${encodeURIComponent(q)}`; // Replace affiliateUrl with official Mercado Livre affiliate links when available.
const affiliateLinks=["https://meli.la/31hbsds","https://meli.la/2EyM8zS","https://meli.la/246f3uU","https://meli.la/3371j1i","https://meli.la/1Rscu23","https://meli.la/1oWBtxH","https://meli.la/2ugniMf","https://meli.la/2umHWe5","https://meli.la/2Ekc4QE","https://meli.la/1LVvZz4"] as const;
export const products:Product[]=[
 ["soundcore-p30i","Soundcore P30i","Soundcore","Melhor equilíbrio geral","Melhor equilíbrio geral","Equilibra recursos para quem quer um TWS versátil.","TWS","Não informado","Não informado","Não informado","Não informado","cotidiano","intermediário"],
 ["jbl-wave-buds-2","JBL Wave Buds 2","JBL","Melhor para uso diário","Uso diário","Uma opção prática para a rotina.","TWS","Não informado","Não informado","Não informado","Não informado","cotidiano","econômico"],
 ["qcy-melobuds-pro","QCY MeloBuds Pro","QCY","Melhor custo-benefício com ANC","Custo-benefício com ANC","Para priorizar cancelamento de ruído sem ir ao segmento premium.","TWS","Não informado","Sim","Não informado","Não informado","trabalho,cotidiano","intermediário"],
 ["soundcore-p20i","Soundcore P20i","Soundcore","Melhor opção econômica","Melhor barato","Alternativa voltada a um orçamento menor.","TWS","Não informado","Não informado","Não informado","Não informado","cotidiano,academia","econômico"],
 ["redmi-buds-6-pro","Redmi Buds 6 Pro","Redmi","Melhor para Android e Xiaomi","Android e Xiaomi","Uma escolha a considerar no ecossistema Xiaomi.","TWS","Não informado","Não informado","Não informado","Não informado","cotidiano","intermediário"],
 ["jbl-tune-beam-2","JBL Tune Beam 2","JBL","Melhor intermediário completo","Intermediário completo","Equilíbrio para diferentes usos do dia.","TWS","Não informado","Não informado","Não informado","Não informado","cotidiano,academia","intermediário"],
 ["galaxy-buds3-pro","Samsung Galaxy Buds3 Pro","Samsung","Melhor para celulares Galaxy","Para Galaxy","Prioriza integração para usuários Galaxy.","TWS","Não informado","Não informado","Não informado","Não informado","cotidiano,trabalho","premium"],
 ["edifier-w820nb-plus","Edifier W820NB Plus","Edifier","Melhor para trabalho e estudo","Trabalho e estudo","Headphone para sessões mais longas de foco.","Headphone","Não informado","Sim","Não informado","Não informado","trabalho","intermediário"],
 ["jbl-tune-770nc","JBL Tune 770NC","JBL","Melhor para viagens e bateria","Viagens e bateria","Headphone para quem busca autonomia e deslocamentos.","Headphone","Não informado","Sim","Não informado","Não informado","viagem","intermediário"],
 ["sony-wh-1000xm5","Sony WH-1000XM5","Sony","Melhor opção premium","Premium","Alternativa de categoria premium para quem aceita investir mais.","Headphone","Não informado","Sim","Não informado","Não informado","viagem,trabalho","premium"]
].map((x,i)=>({id:x[0],slug:x[0],position:i+1,name:x[1],brand:x[2],category:x[3],badge:x[4],description:x[5],type:x[6] as Product["type"],battery:x[7],anc:x[8],codec:x[9],resistance:x[10],use:(x[11] as string).split(","),priceBand:x[12],benefits:["Categoria editorial baseada no perfil de uso","Link para consultar versão e disponibilidade"],limitations:["Especificações devem ser confirmadas na página oficial do produto"],multipoint:"Não informado",image:"",alt:`Placeholder do ${x[1]}`,affiliateUrl:affiliateLinks[i],searchUrl:search(x[1]),featured:i===0,updatedAt:"2026-08-09"}));
